"""Load typed environment settings and generate the backend env template."""

import functools
import textwrap
from pathlib import Path
from typing import Any

from pydantic import Field, SecretStr, ValidationError
from pydantic.fields import FieldInfo
from pydantic_settings import BaseSettings, SettingsConfigDict, SettingsError

from mycode import constants


class Settings(BaseSettings):
    """Environment-controlled configuration shared by Python entrypoints."""

    model_config = SettingsConfigDict(
        env_file=constants.ENV_FILE,
        env_file_encoding="utf-8",
        env_ignore_empty=True,
        extra="ignore",
    )

    database_url: str = Field(
        validation_alias="DATABASE_URL",
        description=(
            "PostgreSQL connection URL. Use Docker Postgres locally and Neon in "
            "production."
        ),
    )
    openai_api_key: SecretStr | None = Field(
        default=None,
        validation_alias="OPENAI_API_KEY",
        description=(
            "API key for the OpenAI platform. Create one at "
            "https://platform.openai.com/api-keys."
        ),
    )
    posthog_api_key: SecretStr | None = Field(
        default=None,
        validation_alias="POSTHOG_API_KEY",
        description=(
            "PostHog project API key used by Python analytics code. Find it in the "
            "PostHog project settings."
        ),
    )


class SettingsConfigurationError(RuntimeError):
    """Raised when environment configuration cannot be loaded or validated."""


def _environment_variable_name(field_name: str, field: FieldInfo) -> str:
    if isinstance(field.validation_alias, str):
        return field.validation_alias
    return field_name.upper()


def _template_value(field: FieldInfo) -> str:
    if field.is_required() or field.default is None:
        return ""
    if isinstance(field.default, bool):
        return str(field.default).lower()
    return str(field.default)


def render_env_template() -> str:
    """Render documented environment placeholders from the Settings model."""
    lines = [
        "# Generated by `uv run python -m mycode.settings`.",
        "# Edit Settings fields and descriptions, then regenerate this file.",
        "",
    ]

    for field_name, field in Settings.model_fields.items():
        requirement = "Required." if field.is_required() else "Optional."
        description = field.description or "No description provided."
        for line in textwrap.wrap(f"{requirement} {description}", width=84):
            lines.append(f"# {line}")
        variable_name = _environment_variable_name(field_name, field)
        lines.extend((f"{variable_name}={_template_value(field)}", ""))

    return "\n".join(lines)


def write_env_template(path: Path = constants.ENV_TEMPLATE_FILE) -> Path:
    """Write the generated environment template and return its path."""
    path.write_text(render_env_template(), encoding="utf-8")
    return path


def _field_from_error_location(
    location: tuple[Any, ...],
) -> tuple[str, FieldInfo] | None:
    if not location:
        return None

    error_name = str(location[0])
    for field_name, field in Settings.model_fields.items():
        variable_name = _environment_variable_name(field_name, field)
        if error_name in (field_name, variable_name):
            return variable_name, field
    return None


def _validation_error_message(error: ValidationError) -> str:
    lines = ["Invalid environment configuration:", ""]

    for issue in error.errors(include_url=False):
        field_match = _field_from_error_location(issue["loc"])
        variable_name = str(issue["loc"][0]) if issue["loc"] else "Unknown setting"
        description = None
        if field_match is not None:
            variable_name, field = field_match
            description = field.description

        if issue["type"] == "missing":
            lines.append(f"- {variable_name} is required but was not provided.")
        else:
            lines.append(f"- {variable_name}: {issue['msg']}.")
        if description:
            lines.append(f"  {description}")
        lines.append("")

    lines.append(
        "Run `uv run python -m mycode.settings` from website/backend to "
        "regenerate .env.template."
    )
    return "\n".join(lines)


def _settings_error_message(error: SettingsError) -> str:
    lines = [
        f"Could not read environment configuration: {error}",
        "",
        "Expected variables:",
    ]
    for field_name, field in Settings.model_fields.items():
        variable_name = _environment_variable_name(field_name, field)
        description = field.description or "No description provided."
        lines.append(f"- {variable_name}: {description}")
    return "\n".join(lines)


@functools.cache
def get_settings() -> Settings:
    """Load and validate the shared settings once per Python process."""
    try:
        return Settings()
    except ValidationError as error:
        raise SettingsConfigurationError(_validation_error_message(error)) from error
    except SettingsError as error:
        raise SettingsConfigurationError(_settings_error_message(error)) from error


def main() -> None:
    """Regenerate the documented backend environment template."""
    path = write_env_template()
    print(f"Generated {path}")


if __name__ == "__main__":
    main()
